"""initial schema

Revision ID: ba1403950ae7
Revises: 
Create Date: 2026-08-21 03:56:39.251878
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'ba1403950ae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('albums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('album_type', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('cover_photo_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_is_deleted'), 'albums', ['is_deleted'], unique=False)
    op.create_index('ix_albums_user_date', 'albums', ['user_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_albums_user_id'), 'albums', ['user_id'], unique=False)
    op.create_index('ix_albums_user_type', 'albums', ['user_id', 'album_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('auth_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_auth_provider_account'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_auth_user_provider')
    )
    op.create_index(op.f('ix_auth_accounts_user_id'), 'auth_accounts', ['user_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['expense_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'parent_id', name='uq_category_user_name_parent')
    )
    op.create_index(op.f('ix_expense_categories_parent_id'), 'expense_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_expense_categories_user_id'), 'expense_categories', ['user_id'], unique=False)
    op.create_index('ix_expense_categories_user_kind', 'expense_categories', ['user_id', 'kind'], unique=False)
    op.create_table('income_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('income_type', sa.String(length=20), nullable=False),
    sa.Column('employer', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_income_source_user_name')
    )
    op.create_index(op.f('ix_income_sources_user_id'), 'income_sources', ['user_id'], unique=False)
    op.create_table('investment_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('broker', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_provider', sa.String(length=40), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_inv_account_user_name')
    )
    op.create_index(op.f('ix_investment_accounts_user_id'), 'investment_accounts', ['user_id'], unique=False)
    op.create_table('investment_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('current_age', sa.Integer(), nullable=True),
    sa.Column('target_age', sa.Integer(), nullable=True),
    sa.Column('current_corpus', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('use_portfolio_value', sa.Boolean(), nullable=False),
    sa.Column('expected_return', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('monthly_investment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('step_up_percent', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('target_amount > 0', name='ck_inv_goal_target_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_goals_user_status', 'investment_goals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_investment_goals_user_id'), 'investment_goals', ['user_id'], unique=False)
    op.create_table('ledger_people',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_person_user_name')
    )
    op.create_index(op.f('ix_ledger_people_is_deleted'), 'ledger_people', ['is_deleted'], unique=False)
    op.create_index('ix_ledger_people_user_archived', 'ledger_people', ['user_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_ledger_people_user_id'), 'ledger_people', ['user_id'], unique=False)
    op.create_table('life_goal_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_life_cat_user_name')
    )
    op.create_index(op.f('ix_life_goal_categories_user_id'), 'life_goal_categories', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action_url', sa.String(length=300), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_due', 'notifications', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('phone_otp_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otp_codes_phone'), 'phone_otp_codes', ['phone'], unique=False)
    op.create_index(op.f('ix_phone_otp_codes_user_id'), 'phone_otp_codes', ['user_id'], unique=False)
    op.create_table('security_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('green_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('green_pin_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pin_lockouts', sa.Integer(), nullable=False),
    sa.Column('unlock_minutes', sa.Integer(), nullable=False),
    sa.Column('mask_ledger_amounts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('privacy_mode_default', sa.Boolean(), nullable=False),
    sa.Column('dashboard_layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_unlocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_token_hash'), 'verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_budget_amount_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_month', 'category_id', name='uq_budget_user_month_cat')
    )
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_index('ix_budgets_user_period', 'budgets', ['user_id', 'period_month'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('merchant', sa.String(length=160), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('attachment_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.create_index('ix_expenses_user_category_date', 'expenses', ['user_id', 'category_id', 'spent_on'], unique=False)
    op.create_index('ix_expenses_user_date', 'expenses', ['user_id', 'spent_on'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('income_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('net_amount >= 0', name='ck_income_net_non_negative'),
    sa.ForeignKeyConstraint(['source_id'], ['income_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_records_is_deleted'), 'income_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_income_records_source_id'), 'income_records', ['source_id'], unique=False)
    op.create_index(op.f('ix_income_records_user_id'), 'income_records', ['user_id'], unique=False)
    op.create_index('ix_income_user_date', 'income_records', ['user_id', 'received_on'], unique=False)
    op.create_index('ix_income_user_period', 'income_records', ['user_id', 'period_month'], unique=False)
    op.create_table('investment_holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_holdings_user_active', 'investment_holdings', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_holdings_user_asset_type', 'investment_holdings', ['user_id', 'asset_type'], unique=False)
    op.create_index(op.f('ix_investment_holdings_account_id'), 'investment_holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_holdings_is_deleted'), 'investment_holdings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_investment_holdings_user_id'), 'investment_holdings', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reminder_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("direction IN ('given','borrowed')", name='ck_ledger_direction'),
    sa.ForeignKeyConstraint(['person_id'], ['ledger_people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_is_deleted'), 'ledger_entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ledger_entries_person_id'), 'ledger_entries', ['person_id'], unique=False)
    op.create_index('ix_ledger_entries_user_direction', 'ledger_entries', ['user_id', 'direction'], unique=False)
    op.create_index('ix_ledger_entries_user_due', 'ledger_entries', ['user_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_index('ix_ledger_entries_user_person', 'ledger_entries', ['user_id', 'person_id'], unique=False)
    op.create_table('life_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('manual_progress', sa.Integer(), nullable=True),
    sa.Column('cover_photo_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['life_goal_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_goals_category_id'), 'life_goals', ['category_id'], unique=False)
    op.create_index(op.f('ix_life_goals_is_deleted'), 'life_goals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_life_goals_user_id'), 'life_goals', ['user_id'], unique=False)
    op.create_index('ix_life_goals_user_status', 'life_goals', ['user_id', 'status'], unique=False)
    op.create_index('ix_life_goals_user_target', 'life_goals', ['user_id', 'target_date'], unique=False)
    op.create_table('memory_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_photos_album_id'), 'memory_photos', ['album_id'], unique=False)
    op.create_index(op.f('ix_memory_photos_user_id'), 'memory_photos', ['user_id'], unique=False)
    op.create_index('ix_photos_user_album', 'memory_photos', ['user_id', 'album_id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tracker_type', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['life_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_is_deleted'), 'checklists', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_checklists_user_id'), 'checklists', ['user_id'], unique=False)
    op.create_index('ix_checklists_user_type', 'checklists', ['user_id', 'tracker_type'], unique=False)
    op.create_table('goal_milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['life_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_milestones_goal_id'), 'goal_milestones', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_milestones_user_id'), 'goal_milestones', ['user_id'], unique=False)
    op.create_index('ix_milestones_user_goal', 'goal_milestones', ['user_id', 'goal_id'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_inv_txn_amount_non_negative'),
    sa.ForeignKeyConstraint(['holding_id'], ['investment_holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_txn_user_date', 'investment_transactions', ['user_id', 'txn_date'], unique=False)
    op.create_index('ix_inv_txn_user_holding', 'investment_transactions', ['user_id', 'holding_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_holding_id'), 'investment_transactions', ['holding_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_user_id'), 'investment_transactions', ['user_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('attachment_key', sa.String(length=512), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_txn_amount_positive'),
    sa.ForeignKeyConstraint(['entry_id'], ['ledger_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['ledger_people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_entry_id'), 'ledger_transactions', ['entry_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_is_voided'), 'ledger_transactions', ['is_voided'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_person_id'), 'ledger_transactions', ['person_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_user_id'), 'ledger_transactions', ['user_id'], unique=False)
    op.create_index('ix_ledger_txn_user_date', 'ledger_transactions', ['user_id', 'txn_date'], unique=False)
    op.create_index('ix_ledger_txn_user_entry', 'ledger_transactions', ['user_id', 'entry_id'], unique=False)
    op.create_index('ix_ledger_txn_user_person_date', 'ledger_transactions', ['user_id', 'person_id', 'txn_date'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('checklist_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('album_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index('ix_checklist_items_user_done', 'checklist_items', ['user_id', 'is_completed'], unique=False)
    op.create_index(op.f('ix_checklist_items_user_id'), 'checklist_items', ['user_id'], unique=False)
    op.create_index('ix_checklist_items_user_list', 'checklist_items', ['user_id', 'checklist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checklist_items_user_list', table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_user_id'), table_name='checklist_items')
    op.drop_index('ix_checklist_items_user_done', table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index('ix_ledger_txn_user_person_date', table_name='ledger_transactions')
    op.drop_index('ix_ledger_txn_user_entry', table_name='ledger_transactions')
    op.drop_index('ix_ledger_txn_user_date', table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_user_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_person_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_is_voided'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_entry_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_investment_transactions_user_id'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_holding_id'), table_name='investment_transactions')
    op.drop_index('ix_inv_txn_user_holding', table_name='investment_transactions')
    op.drop_index('ix_inv_txn_user_date', table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index('ix_milestones_user_goal', table_name='goal_milestones')
    op.drop_index(op.f('ix_goal_milestones_user_id'), table_name='goal_milestones')
    op.drop_index(op.f('ix_goal_milestones_goal_id'), table_name='goal_milestones')
    op.drop_table('goal_milestones')
    op.drop_index('ix_checklists_user_type', table_name='checklists')
    op.drop_index(op.f('ix_checklists_user_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_is_deleted'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index('ix_photos_user_album', table_name='memory_photos')
    op.drop_index(op.f('ix_memory_photos_user_id'), table_name='memory_photos')
    op.drop_index(op.f('ix_memory_photos_album_id'), table_name='memory_photos')
    op.drop_table('memory_photos')
    op.drop_index('ix_life_goals_user_target', table_name='life_goals')
    op.drop_index('ix_life_goals_user_status', table_name='life_goals')
    op.drop_index(op.f('ix_life_goals_user_id'), table_name='life_goals')
    op.drop_index(op.f('ix_life_goals_is_deleted'), table_name='life_goals')
    op.drop_index(op.f('ix_life_goals_category_id'), table_name='life_goals')
    op.drop_table('life_goals')
    op.drop_index('ix_ledger_entries_user_person', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_user_due', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_user_direction', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_person_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_is_deleted'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_investment_holdings_user_id'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_is_deleted'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_account_id'), table_name='investment_holdings')
    op.drop_index('ix_holdings_user_asset_type', table_name='investment_holdings')
    op.drop_index('ix_holdings_user_active', table_name='investment_holdings')
    op.drop_table('investment_holdings')
    op.drop_index('ix_income_user_period', table_name='income_records')
    op.drop_index('ix_income_user_date', table_name='income_records')
    op.drop_index(op.f('ix_income_records_user_id'), table_name='income_records')
    op.drop_index(op.f('ix_income_records_source_id'), table_name='income_records')
    op.drop_index(op.f('ix_income_records_is_deleted'), table_name='income_records')
    op.drop_table('income_records')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index('ix_expenses_user_date', table_name='expenses')
    op.drop_index('ix_expenses_user_category_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_budgets_user_period', table_name='budgets')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_token_hash'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    op.drop_table('security_settings')
    op.drop_index(op.f('ix_phone_otp_codes_user_id'), table_name='phone_otp_codes')
    op.drop_index(op.f('ix_phone_otp_codes_phone'), table_name='phone_otp_codes')
    op.drop_table('phone_otp_codes')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_due', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_life_goal_categories_user_id'), table_name='life_goal_categories')
    op.drop_table('life_goal_categories')
    op.drop_index(op.f('ix_ledger_people_user_id'), table_name='ledger_people')
    op.drop_index('ix_ledger_people_user_archived', table_name='ledger_people')
    op.drop_index(op.f('ix_ledger_people_is_deleted'), table_name='ledger_people')
    op.drop_table('ledger_people')
    op.drop_index(op.f('ix_investment_goals_user_id'), table_name='investment_goals')
    op.drop_index('ix_inv_goals_user_status', table_name='investment_goals')
    op.drop_table('investment_goals')
    op.drop_index(op.f('ix_investment_accounts_user_id'), table_name='investment_accounts')
    op.drop_table('investment_accounts')
    op.drop_index(op.f('ix_income_sources_user_id'), table_name='income_sources')
    op.drop_table('income_sources')
    op.drop_index('ix_expense_categories_user_kind', table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_user_id'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_parent_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_auth_accounts_user_id'), table_name='auth_accounts')
    op.drop_table('auth_accounts')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_albums_user_type', table_name='albums')
    op.drop_index(op.f('ix_albums_user_id'), table_name='albums')
    op.drop_index('ix_albums_user_date', table_name='albums')
    op.drop_index(op.f('ix_albums_is_deleted'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
